## Import Libraries

In [1]:
import pandas as pd
import numpy as np

## Read Dataset

In [2]:
df=pd.read_csv("Iris.csv")
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

## Initial Inspection

In [3]:
df.shape

(150, 5)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [5]:
df.describe()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count     150.000000    150.000000     150.000000    150.000000
mean        5.843333      3.054000       3.758667      1.198667
std         0.828066      0.433594       1.764420      0.763161
min         4.300000      2.000000       1.000000      0.100000
25%         5.100000      2.800000       1.600000      0.300000
50%         5.800000      3.000000       4.350000      1.300000
75%         6.400000      3.300000       5.100000      1.800000
max         7.900000      4.400000       6.900000      2.500000

## Display of null values 

In [6]:
print(df[df.isna().any(axis=1)])

Empty DataFrame
Columns: [SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm, Species]
Index: []


In [7]:
df1=df.copy(deep=True)

In [8]:
df1.isna().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

## Dropping of Rows/Columns

In [9]:
df1.dropna(axis=0,inplace=True) # inplace to overwrite in same record axis=0 - drop rows

In [10]:
df1.isna().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [11]:
df.isna().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [12]:
df2=df.copy(deep=True)
df2.isna().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

## Imputing Missing Values

In [13]:
m=df2["PetalLengthCm"].median()
df2["PetalLengthCm"]=df2["PetalLengthCm"].fillna(m)
df2.iloc[[20,37],:]

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
20            5.4           3.4            1.7           0.2  Iris-setosa
37            4.9           3.1            1.5           0.1  Iris-setosa

In [14]:
df=pd.read_csv("Iris.csv")
from sklearn.impute import SimpleImputer
imp=SimpleImputer(missing_values=np.nan,strategy='mean')
df_n=df.iloc[:,0:4]
imputed=imp.fit_transform(df_n)
imputed

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [15]:
names=["sepal_len","sepal_width","petal_len","petal_width"]
df3=pd.DataFrame(imputed,columns=names)

In [16]:
df3["Species"]=df["Species"].fillna(method="bfill")
df3.iloc[[28],:]

sepal_len  sepal_width  petal_len  petal_width      Species
28        5.2          3.4        1.4          0.2  Iris-setosa

In [17]:
df4=df3.copy(deep=True)
df4.shape

(150, 5)

In [18]:
df4.isna().sum()

sepal_len      0
sepal_width    0
petal_len      0
petal_width    0
Species        0
dtype: int64

## Handling Categorical Data

In [19]:
df4["Species"].value_counts()

Iris-setosa        50
Iris-virginica     50
Iris-versicolor    50
Name: Species, dtype: int64

In [20]:
mapping={"Iris-setosa":3,
         "Iris-virginica":2,
        "Iris-versicolor":1}
df4["Species"]=df4["Species"].map(mapping)

In [21]:
df4.head()

sepal_len  sepal_width  petal_len  petal_width  Species
0        5.1          3.5        1.4          0.2        3
1        4.9          3.0        1.4          0.2        3
2        4.7          3.2        1.3          0.2        3
3        4.6          3.1        1.5          0.2        3
4        5.0          3.6        1.4          0.2        3

In [22]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(df3['Species'])
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## Inverse Encoding

In [23]:
actual=le.inverse_transform(y)

In [24]:
actual

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

## One hot Encoding

In [25]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
X=df3[["Species"]]
ohe.fit_transform(X).toarray()

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [26]:
pd.get_dummies(df['Species'])

Iris-setosa  Iris-versicolor  Iris-virginica
0              1                0               0
1              1                0               0
2              1                0               0
3              1                0               0
4              1                0               0
..           ...              ...             ...
145            0                0               1
146            0                0               1
147            0                0               1
148            0                0               1
149            0                0               1

[150 rows x 3 columns]

## Feature Scaling

In [27]:
from sklearn.preprocessing import MinMaxScaler
x=df4.iloc[:,0:5]
mmscaler = MinMaxScaler()
x_scaled = mmscaler.fit_transform(x)

In [28]:
x_scaled

array([[0.22222222, 0.625     , 0.06779661, 0.04166667, 1.        ],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667, 1.        ],
       [0.11111111, 0.5       , 0.05084746, 0.04166667, 1.        ],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667, 1.        ],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667, 1.        ],
       [0.30555556, 0.79166667, 0.11864407, 0.125     , 1.        ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333, 1.        ],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667, 1.        ],
       [0.02777778, 0.375     , 0.06779661, 0.04166667, 1.        ],
       [0.16666667, 0.45833333, 0.08474576, 0.        , 1.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667, 1.        ],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667, 1.        ],
       [0.13888889, 0.41666667, 0.06779661, 0.        , 1.        ],
       [0.        , 0.41666667, 0.01694915, 0.        , 1.        ],
       [0.41666667, 0.83333333, 0.

## Select significant features

In [29]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2,f_regression
y=df4['Species'] # numeric predictor variable so, use f_regression in selectKbest
#if it is categorical use chi2
X=df4.iloc[:,0:4]
selectk = SelectKBest(chi2, k=2)
X_new=selectk.fit_transform(X, y)
selectk.pvalues_

array([4.47651499e-03, 1.65754167e-01, 5.94344354e-26, 2.50017968e-15])

In [30]:
df_new=pd.DataFrame(X_new)
df_new

0    1
0    1.4  0.2
1    1.4  0.2
2    1.3  0.2
3    1.5  0.2
4    1.4  0.2
..   ...  ...
145  5.2  2.3
146  5.0  1.9
147  5.2  2.0
148  5.4  2.3
149  5.1  1.8

[150 rows x 2 columns]

In [31]:
from sklearn.model_selection import train_test_split
X=df3.iloc[:,0:4]
y=df3['Species']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=1,shuffle=True)

In [32]:
X_train.shape

(120, 4)

In [33]:
X_test.shape

(30, 4)

In [34]:
df3.shape

(150, 5)

In [35]:
y_train.value_counts()

Iris-virginica     44
Iris-setosa        39
Iris-versicolor    37
Name: Species, dtype: int64